
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1yALlNstTgNJIoOJ3UyADZXgN4FAWCs',
    appId: '1:779278452411:web:500154b95386000fd88b9e',
    messagingSenderId: '779278452411',
    projectId: 'concern-app-3126b',
    authDomain: 'concern-app-3126b.firebaseapp.com',
    storageBucket: 'concern-app-3126b.firebasestorage.app',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJpEC-6uKD1NkyxRKlL-3hYh_ti5ZPxc',
    appId: '1:779278452411:android:65687d68175b6b0fd88b9e',
    messagingSenderId: '779278452411',
    projectId: 'concern-app-3126b',
    storageBucket: 'concern-app-3126b.firebasestorage.app',
  );
}


